tweet24_server:
  build: ./server/
  restart: always
  ports:
    - "127.0.0.1:15001:15001"
  environment:
    - TOPIC_NAME=tweet24
    - KAFKA_CLIENT_URI=192.168.31.242:2181
    - HAPI_SERVER_PORT=15001
    - HAPI_SERVER_HOST=localhost

tweet24_consumer:
  build: ./consumer/
  restart: always
  ports:
    - "127.0.0.1:15002:15002"
  environment:
    - TOPIC_NAME=tweet24
    - WEB_SOCKET_SERVER_PORT=15002
    - KAFKA_CLIENT_URI=192.168.31.242:2181

